name: run checks
on:
  push:
    branches-ignore:
      - master
jobs:
  check:
    name: Check with `su6 all`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - uses: yezz123/setup-uv@v4
      - run: uv venv && uv pip install su6[all] .[dev,all]
      - run: su6 all --coverage 100
